#!/bin/bash

# run with sudo sddm / kde example

echo "=== Installing audio support ==="
pacman -S --noconfirm --needed pipewire-alsa #pipewire #pipewire-pulse #pipewire-jack #wireplumber

echo "=== Setting up audio support ==="
mkdir -p /etc/pipewire
cp -r /usr/share/pipewire/pipewire* /etc/pipewire

# edit final lines of 
#/etc/pipewire/pipewire.conf just before closing ]
# { path = "/usr/bin/wireplumber" args = "" }
# { path = "/usr/bin/pipewire" args= "-c pipewire-pulse.conf" }

tac /etc/pipewire/pipewire.conf | \
  sed '0,/^]$/{s/^]$/]\n    { path = "\/usr\/bin\/pipewire" args = "-c pipewire-pulse.conf" }\n    { path = "\/usr\/bin\/wireplumber" args = "" }/}' | \
  tac | tee /tmp/pipewire.conf.tmp > /dev/null && \
  mv /tmp/pipewire.conf.tmp /etc/pipewire/pipewire.conf

mkdir -p "/home/$SUDO_USER/.config/autostart/"
cat > "/home/$SUDO_USER/.config/autostart/pipewire.desktop" <<'EOF'
[Desktop Entry]
Type=Application
Name=Pipewire
Exec=/usr/bin/pipewire
X-KDE-autostart-phase=1
EOF

chmod +x "/home/$SUDO_USER/.config/autostart/pipewire.desktop"
